[build]
  command = "npm run build"
  publish = "build/"
  # functions = "functions/"

[build.environment]
  NODE_ENV = "development"
  NODE_VERSION = "--lts"
  NPM_VERSION = "6.14.8"
  RUBY_VERSION = "default"
